### ISSUE TITLE
makeFieldEntry not compiling

### ISSUE THREAD

**Issue by grosch** [nodes-vapor/submissions#11]
I was using this as one of my `fieldEntries()` items:

```swift
makeFieldEntry(keyPath: \.contractStart, label: "Monthly Rate:", isOptional: true),
```

As of beta 3 that no longer compiles.  It underlines the keypath and says type of expression is ambiguous without more context.  If I remove the `isOptional` field it compiles.

**Comment by siemensikkema** [comment]
I renamed `isOptional` to `isRequired`. I mentioned this in the release notes :). It was in response to https://github.com/nodes-vapor/submissions/issues/9.
