### ISSUE TITLE
Amend instructions

### ISSUE THREAD

**Issue by grosch** [nodes-vapor/submissions#2]
In the installation instructions please remind people to add Submissions to their app target dependencies.  Took me a bit of futzing before I remembered I needed to do that.

**Comment by siemensikkema** [comment]
Agreed! I'll do that right away.

**Comment by siemensikkema** [comment]
@grosch I also forgot to mention that you need to register a provider in `configure.swift`:
```swift
try services.register(SubmissionsProvider())
```

I've added this to the documentation but I found something that doesn't quite make sense and I want to fix it and see what the impact on the documentation before I push.

**Comment by siemensikkema** [comment]
I updated the docs now.
