### ISSUE TITLE
Change data on the way in

### ISSUE THREAD

**Issue by grosch** [nodes-vapor/submissions#4]
How do we modify the data on the way in?  For example, my model has a `Date` field.  Obviously I don't want that showing up in the text box as-is.  I need to run it through some type of `DateFormatter` before it's filled in as the value of the field, for example when I'm doing an edit request.

**Comment by siemensikkema** [comment]
Good question! Ideally we would have control over the en/decoder that's being used so we could use a custom `dateDecodingStrategy` and `dateEncodingStrategy` but I don't see how we'd do that.
I haven't gotten around to testing it but my idea for dealing with this was to have date as a `String` on your `Submission` struct and `Create` and do the conversion there, using a computed var for instance.
This situation also calls for another tag ("dategroup") to set the correct input type. I'll try to get an example up in my [test project](https://github.com/siemensikkema/submissions-host) as soon as I have time again.

**Comment by grosch** [comment]
I forked this thinking I could help with some templates, but it's not the full "project", like with a .xcodeproj file, so I wasn't sure how to participate.
