### ISSUE TITLE
Add 'id' to textgroup

### ISSUE THREAD

**Issue by grosch** [nodes-vapor/submissions#6]
Suggest the textgroup expansion should set the `id` as well as the `name` so that it's accessible from javascript.

**Comment by siemensikkema** [comment]
Agreed. Do you see any problem with setting it to the value of the `key`, so like `name`?

**Comment by grosch** [comment]
That’s what I’d do.

**Comment by siemensikkema** [comment]
I pushed it to master. It will be part of the next release.
